#' @export
quincunx_pgs_report <- function(scores_obj, file = basename(tempfile(pattern = 'pgs_report_', fileext = '.html'))) {

  template <- system.file('templates', 'quincunx_pgs_report.Rmd', package = 'hapiviz')
  report <- rmarkdown::render(template, params = list(pgs = scores_obj), output_file = file, quiet = TRUE)

  # RStudio Viewer only works with a source file written to a session temporary
  # directory (i.e. files with paths generated by the tempfile function)
  # https://stackoverflow.com/questions/28732232/rstudio-viewer-pane-not-working
  tmp_report <- file.path(tempdir(), basename(report))

  if (rstudioapi::hasFun("viewer") && file.copy(report, tmp_report, overwrite = TRUE)) {
    rstudioapi::callFun("viewer", tmp_report)
  } else {
    browseURL(report)
  }
}
