#' @export
quincunx_ppm_report <- function(ppm_obj, file) {

  template <- system.file('templates', 'quincunx_ppm_report.Rmd', package = 'hapiviz')
  report <- rmarkdown::render(template, params = list(pgs = ppm_obj), output_file = file, quiet = TRUE)

  # RStudio Viewer only works with a source file written to a session temporary
  # directory (i.e. files with paths generated by the tempfile function)
  # https://stackoverflow.com/questions/28732232/rstudio-viewer-pane-not-working
  tmp_report <- file.path(tempdir(), basename(report))

  if (rstudioapi::hasFun("viewer") && file.copy(report, tmp_report, overwrite = TRUE)) {
    rstudioapi::callFun("viewer", tmp_report)
  } else {
    browseURL(report)
  }
}
